[package]
name = "rmusic"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
directories = "6.0.0"
ratatui = "0.29.0"
rodio = "0.20.1"
thirtyfour = "0.35.0"
tokio = { version = "1.43.0", features = ["full"] }
